version: '3.1'

services:
#  server:
#    container_name: backend
#    build: .
#    environment:
#      db_url: mongodb://techchallenge:password@mongo:27017/
#      db_user: techchallenge
#      db_password: password
#    ports:
#      - 8083:8090

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: techchallenge
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 8082:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: techchallenge
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://techchallenge:password@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"