version: '3.1'

services:
  server:
    container_name: backend
    build: .
    environment:
      DB_URL: mongodb://techchallenge:password@mongo:27017/
      DB_DATABASE: TechChallenge
    ports:
      - 8083:8080
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 700M

  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: techchallenge
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 8082:27017